version: '3.8'

services:
  users:
    image: mongo:latest
    container_name: users-service
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - microservices-net

  categories:
    image: postgres:latest
    container_name: categories-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: categories_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    networks:
      - microservices-net

  products:
    image: mongo:latest
    container_name: products-service
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - microservices-net

  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users
      - categories
      - products
    networks:
      - microservices-net

networks:
  microservices-net:
